<div class="footer-large">
    <div class="clock center" id="clock"></div>
    <div class="footer-date">
        <div class="day" id="day"></div>
        <div class="date" id="date"></div>
    </div>
    <a class="logo center" href="https://www.clearsite.nl/" target="_blank">
        <img class="logo-img" src="../../img/clearsite.png" alt="logo">
        <span class="logo-text"><?= ApplicationController::load_svg('logo-text') ?></span>
    </a>
    <span class="footer-fade"></span>
</div>

<div class="footer">
    <span class="footer-fade"></span>
    <div class="footer-copy center">
        <a href="https://www.clearsite.nl/" target="_blank">&copy; Clearsite 2020</a>
    </div>
</div>