<!doctype html>

<!--[if IE]>
<?= require_once ERROR_UNSUPPORTED ?>
<![endif]-->

<html lang="en">
<head>
    <!--Define url-->
    <script>window.app = {baseUrl: <?php print json_encode($this->urlArr['baseUrl']); ?> };</script>

    <!--Page Title-->
    <title><?= PAGENAME ?></title>

    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="<?= PageController::url('img/favicon/apple-touch-icon.png') ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= PageController::url('img/favicon/favicon-32x32.png') ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= PageController::url('img/favicon/favicon-16x16.png') ?>">
    <link rel="manifest" href="<?= PageController::url('img/favicon/site.webmanifest') ?>">
    <link rel="mask-icon" href="<?= PageController::url('img/favicon/safari-pinned-tab.svg') ?>" color="#0265dd">
    <!--For the favicons I recommend using https://realfavicongenerator.net/, this will give you all the icons for every browser.-->

    <!--Meta and CSS-->
    <?php
    require_once META;
    require_once CSS;
    ?>
</head>
<body>
<!-- Loading icon -->
<div id="load"><span id="load-text">Laden...</span></div>

<!--Navbar-->
<?php $this->get_part('navbar'); ?>

<!--Content-->
<section class="content" id="content">
