<nav class="navbar">
    <div class="logo center">
        <img class="logo-img" src="../../img/jpg/logo.jpg" alt="logo">
        <span class="logo-text"><?= ApplicationController::load_svg('logo-text') ?></span>
    </div>
    <button class="hamburger hamburger--spin" type="button">
        <span class="hamburger-box">
            <span class="hamburger-inner"></span>
        </span>
    </button>
    <div class="menu">

    </div>
</nav>