<style>
    html, body {
        margin: 0;
        padding: 0;
        overflow: hidden;
    }

    .content {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>

<div style="height: 100%; display: flex; align-items: center; justify-content: center; background-color: #D6D6D6;">
    <div style="text-align: center;">
        <div style="color: #FFAA00; font-size: 4vmin; letter-spacing: .5vmin;">
            <h1>ERROR 403</h1>
        </div>
        <div>
            <h3 style="font-size: 3vmin;">You have no acces to this page!</h3>
            <h2 style="font-size: 2.5vmin;">You will be redirected to the homepage.</h2>
        </div>
    </div>
</div>