<style>
    html, body {
        margin: 0;
        padding: 0;
        overflow: hidden;
    }
</style>

<div style="display: flex; justify-content: center; align-items: center; overflow: hidden; background-color: #000000; height: calc(100vh - 10vmin); padding: 5vmin;">
    <div style="font-family: monospace; font-weight: 200; text-align: center;">
        <div style="color: #FF0000; font-size: 4vmin; letter-spacing: 1vmin;">
            <h1>ERROR 404</h1>
        </div>
        <div style="color: #FFFFFF; font-size: 2vmin;">
            <h3>This page does not exist!</h3>
            <h3>You will be redirected to the homepage.</h3>
        </div>
    </div>
</div>