<style>
    html, body {
        margin: 0;
        padding: 0;
        z-index: 10;
        overflow: hidden;
    }
</style>

<div style="color: white; font-size: 24px; background-color: black; padding: 18px; height: 100vh; width: 100vw; display: table-cell; vertical-align: middle; text-align: center;">
    <span style='font-family: monospace, sans-serif; color: red; font-size: 32px; font-weight: 800; text-transform: uppercase;'>
        <b>Internet Explorer is not supported on this site!</b>
    </span>
    <br>
    <span>This site uses modern technology that is <b>not</b> supported by IE! Please switch to a modern browser such as: </span>
    <a style='color: #757575' href='https://www.google.com/intl/nl_nl/chrome/' target='_blank'>Google Chrome</a>,
    <a style='color: #757575' href='https://www.microsoft.com/nl-nl/edge' target='_blank'>Microsoft Edge</a> or
    <a style='color: #757575' href='https://www.mozilla.org/nl/firefox/new/' target='_blank'>Firefox</a>!
</div>