<!--Main CSS-->
<link rel="stylesheet" href="<?= $this->url('style/css/main.css') ?>">

<!--Fonts-->
<link rel="stylesheet" href="<?= $this->url('style/font/font.css') ?>">

<!--Hamburgers-->
<link rel="stylesheet" href="<?= $this->url('style/css/hamburgers.min.css') ?>">

<!--Icons-->
<link rel="stylesheet" href="<?= $this->url('style/css/icons/brands.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/icons/fontawesome.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/icons/regular.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/icons/solid.min.css') ?>">