<!--JQuery-->
<script type="text/javascript" src="<?= $this->url('js/jquery-3.4.1.min.js') ?>"></script>

<!--Main JS-->
<script type="text/javascript" src="<?= $this->url('js/main.js') ?>"></script>

<!--Icons-->
<script type="text/javascript" src="<?= $this->url('js/icons/brands.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->url('js/icons/fontawesome.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->url('js/icons/regular.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->url('js/icons/solid.min.js') ?>"></script>