<div class="project-item">
    <div class="project-head">
        <img class="project-img" src="../../img/projecten/project_3.jpg" alt="project_3">
        <div class="project-title">Project 3</div>
        <p class="project-detail">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna ultricies, suscipit felis id, tempor metus. Nulla mollis aliquet mauris et dictum. Nam risus ligula, ultricies at purus ac, bibendum maximus odio. Maecenas dui
            velit, malesuada eget lacus at, mollis fermentum leo. Fusce non libero vel lacus pellentesque sagittis. Quisque lectus tellus, suscipit eget elementum blandit, ornare at dui. Cras lectus enim, viverra sed ex ac, vulputate viverra nulla.
        </p>
    </div>
    <div class="project-info">
        <h3>Lorem ipsum</h3>
        <p class="project-text">
            Nulla commodo sollicitudin libero, porttitor dapibus enim iaculis non. Sed aliquet quam vitae volutpat porta. Vivamus sapien turpis, vehicula sit amet cursus eu, fermentum quis quam. Morbi tincidunt mi at leo tempor, id mollis odio
            fringilla. Suspendisse nunc ante, tempor placerat ante sit amet, pulvinar iaculis lorem. Suspendisse fringilla aliquet augue, iaculis luctus libero blandit sed. Aliquam metus elit, pulvinar porta consectetur malesuada, tempus quis
            nisl.
        </p>
        <h3>Lorem ipsum</h3>
        <p class="project-text">
            Etiam at finibus nisi, sit amet sagittis magna. Aliquam sollicitudin orci in ullamcorper mollis. Nullam lectus lectus, euismod ac felis non, maximus aliquet tellus. Duis maximus, nisl non maximus sodales, elit nibh sollicitudin lacus, vel
            tincidunt nulla nisi non urna. Curabitur et nulla elit. Curabitur et mi ut quam venenatis posuere.
        </p>
    </div>
</div>