<div class="project_list-large">
    <div class="project-row">
        <div class="project-grid">
            <a class="project-item center" href="<?= PageController::url('projecten/project_1') ?>">
                <img class="project-img" src="../img/projecten/project_1.jpg" alt="project_1">
                <div class="project-title">Project 1</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_2') ?>">
                <img class="project-img" src="../img/projecten/project_2.jpg" alt="project_2">
                <div class="project-title">Project 2</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_3') ?>">
                <img class="project-img" src="../img/projecten/project_3.jpg" alt="project_3">
                <div class="project-title">Project 3</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_4') ?>">
                <img class="project-img" src="../img/projecten/project_4.jpg" alt="project_4">
                <div class="project-title">Project 4</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_5') ?>">
                <img class="project-img" src="../img/projecten/project_5.jpg" alt="project_5">
                <div class="project-title">Project 5</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_6') ?>">
                <img class="project-img" src="../img/projecten/project_6.jpg" alt="project_6">
                <div class="project-title">Project 6</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_7') ?>">
                <img class="project-img" src="../img/projecten/project_7.jpg" alt="project_7">
                <div class="project-title">Project 7</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_8') ?>">
                <img class="project-img" src="../img/projecten/project_8.jpg" alt="project_8">
                <div class="project-title">Project 8</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_9') ?>">
                <img class="project-img" src="../img/projecten/project_9.jpg" alt="project_9">
                <div class="project-title">Project 9</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_10') ?>">
                <img class="project-img" src="../img/projecten/project_10.jpg" alt="project_10">
                <div class="project-title">Project 10</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_11') ?>">
                <img class="project-img" src="../img/projecten/project_11.jpg" alt="project_11">
                <div class="project-title">Project 11</div>
            </a>
            <a class="project-item center" href="<?= PageController::url('projecten/project_12') ?>">
                <img class="project-img" src="../img/projecten/project_12.jpg" alt="project_12">
                <div class="project-title">Project 12</div>
            </a>
            <a class="project-item project-new center" href="<?= PageController::url('project_aanmaken') ?>">
                <div class="project-icon"><i class="fas fa-6x fa-plus"></i></div>
            </a>
        </div>
    </div>
</div>

<div class="project_list">
    <div class="project-row">
        <a class="project-item" href="<?= PageController::url('projecten/project_1') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_1.jpg" alt="project_1">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 1</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_2') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_2.jpg" alt="project_2">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 2</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_3') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_3.jpg" alt="project_3">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 3</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_4') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_4.jpg" alt="project_4">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 4</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_5') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_5.jpg" alt="project_5">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 5</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_6') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_6.jpg" alt="project_6">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 6</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_7') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_7.jpg" alt="project_7">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 7</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_8') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_8.jpg" alt="project_8">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 8</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_9') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_9.jpg" alt="project_9">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 9</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_10') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_10.jpg" alt="project_10">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 10</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_11') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_11.jpg" alt="project_11">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 11</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item" href="<?= PageController::url('projecten/project_12') ?>">
            <div class="img-row">
                <img class="project-img" src="../img/projecten/project_12.jpg" alt="project_12">
            </div>
            <div class="project-body">
                <h1 class="project-title">Project 12</h1>
                <p class="project-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum neque orci, pharetra eget dictum placerat, vestibulum in erat. Donec molestie viverra nibh ultrices consequat. Nulla porttitor vehicula sollicitudin. In hac
                    habitasse platea dictumst. Maecenas eros massa, imperdiet sed ultricies at, dapibus quis diam. Nunc scelerisque sit amet odio sed commodo. Suspendisse potenti. Suspendisse vel lorem laoreet, lacinia dolor non, accumsan leo.
                </p>
            </div>
        </a>
        <a class="project-item project-new center" href="<?= PageController::url('project_aanmaken') ?>">
            <div class="project-icon"><i class="fas fa-6x fa-plus"></i></div>
        </a>
    </div>
</div>

<div class="project_list-medium">
    <div class="project-row">
        <div class="project-grid">
            <a class="project-item">

            </a>
        </div>
    </div>
</div>

<div class="project_list-small">
    <div class="project-row">

    </div>
</div>