<?php if (!empty($this->pageObj->Project)) : ?>
    <div class="project_page">
        <span class="project-chevron chevron-left center">
            <a href="<?= PageController::url($this->pageObj->Prev) ?>"><i class="fas fa-chevron-left"></i></a>
        </span>
        <div class="project-row center">
            <?= $this->pageObj->Project ?>
        </div>
        <span class="project-chevron chevron-right center">
            <a href="<?= PageController::url($this->pageObj->Next) ?>"><i class="fas fa-chevron-right"></i></a>
        </span>
    </div>

    <div class="project_page-small">
        <div class="project-row">
            <?= $this->pageObj->Project ?>
        </div>
    </div>
<?php else : ?>
    <?php $this->get_part('errors/404'); ?>
<?php endif; ?>